import type { Product } from "../types";

/** Placeholder imagery reuses hero assets until dedicated product photos exist. */
export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "turkish-jacquard-pink-cord",
    slug: "turkish-jacquard-black-abaya-pink-cord",
    nameKey: "turkishJacquardPinkCord",
    priceTRY: 2890,
    compareAtPriceTRY: 3210,
    badge: "sale",
    rating: 4.9,
    reviewsCount: 38,
    sku: "20103501",
    weightKg: 1,
    inStock: true,
    sizes: [
      { id: "52", name: "52" },
      { id: "54", name: "54" },
      { id: "56", name: "56" },
      { id: "58", name: "58" },
      { id: "60", name: "60" },
    ],
    includesSheila: true,
    specs: [
      { id: "design" },
      { id: "silhouette" },
      { id: "fabric" },
      { id: "color" },
      { id: "finishes", hasBullets: true },
      { id: "sleeves" },
      { id: "closure" },
      { id: "sheila" },
    ],
    colors: [
      {
        id: "black",
        nameKey: "black",
        swatch: "black",
        images: [
          "/imgs/hero-slide-3.jpg",
          "/imgs/hero-slide-1.jpg",
          "/imgs/hero-slide-2.jpg",
        ],
      },
    ],
  },
  {
    id: "linen-aline",
    slug: "classic-linen-aline-abaya",
    nameKey: "linenAline",
    priceTRY: 1890,
    rating: 5.0,
    reviewsCount: 44,
    sku: "LL-AL-01",
    weightKg: 0.9,
    inStock: true,
    sizes: [
      { id: "52", name: "52" },
      { id: "54", name: "54" },
      { id: "56", name: "56" },
      { id: "58", name: "58" },
      { id: "60", name: "60" },
    ],
    includesSheila: true,
    specs: [
      { id: "design" },
      { id: "silhouette" },
      { id: "fabric" },
      { id: "color" },
      { id: "finishes", hasBullets: true },
      { id: "sleeves" },
      { id: "closure" },
      { id: "sheila" },
    ],
    colors: [
      {
        id: "sand",
        nameKey: "sand",
        swatch: "sand",
        images: ["/imgs/hero-slide-1.jpg", "/imgs/hero-slide-2.jpg"],
      },
      {
        id: "olive",
        nameKey: "olive",
        swatch: "olive",
        images: ["/imgs/hero-slide-2.jpg", "/imgs/hero-slide-3.jpg"],
      },
      {
        id: "black",
        nameKey: "black",
        swatch: "black",
        images: ["/imgs/hero-slide-3.jpg", "/imgs/hero-slide-1.jpg"],
      },
    ],
  },
  {
    id: "olive-heritage",
    slug: "olive-heritage-embroidered-abaya",
    nameKey: "oliveHeritage",
    priceTRY: 2450,
    compareAtPriceTRY: 2890,
    badge: "sale",
    rating: 4.8,
    reviewsCount: 29,
    sku: "LL-OH-02",
    weightKg: 1.1,
    inStock: true,
    sizes: [
      { id: "52", name: "52" },
      { id: "54", name: "54" },
      { id: "56", name: "56" },
      { id: "58", name: "58" },
      { id: "60", name: "60" },
    ],
    includesSheila: true,
    specs: [
      { id: "design" },
      { id: "silhouette" },
      { id: "fabric" },
      { id: "color" },
      { id: "finishes", hasBullets: true },
      { id: "sleeves" },
      { id: "closure" },
      { id: "sheila" },
    ],
    colors: [
      {
        id: "olive",
        nameKey: "olive",
        swatch: "olive",
        images: [
          "/imgs/hero-slide-2.jpg",
          "/imgs/hero-slide-1.jpg",
          "/imgs/hero-slide-3.jpg",
        ],
      },
      {
        id: "charcoal",
        nameKey: "charcoal",
        swatch: "charcoal",
        images: ["/imgs/hero-slide-3.jpg", "/imgs/hero-slide-2.jpg"],
      },
    ],
  },
  {
    id: "midnight-silk",
    slug: "midnight-silk-linen-abaya",
    nameKey: "midnightSilk",
    priceTRY: 3200,
    badge: "new",
    rating: 4.9,
    reviewsCount: 19,
    sku: "LL-MS-03",
    weightKg: 0.85,
    inStock: true,
    sizes: [
      { id: "52", name: "52" },
      { id: "54", name: "54" },
      { id: "56", name: "56" },
      { id: "58", name: "58" },
      { id: "60", name: "60" },
    ],
    includesSheila: true,
    specs: [
      { id: "design" },
      { id: "silhouette" },
      { id: "fabric" },
      { id: "color" },
      { id: "finishes", hasBullets: true },
      { id: "sleeves" },
      { id: "closure" },
      { id: "sheila" },
    ],
    colors: [
      {
        id: "black",
        nameKey: "black",
        swatch: "black",
        images: ["/imgs/hero-slide-3.jpg", "/imgs/hero-slide-1.jpg"],
      },
      {
        id: "charcoal",
        nameKey: "charcoal",
        swatch: "charcoal",
        images: ["/imgs/hero-slide-1.jpg", "/imgs/hero-slide-3.jpg"],
      },
    ],
  },
  {
    id: "travel-kimono",
    slug: "travel-kimono-abaya",
    nameKey: "travelKimono",
    priceTRY: 1650,
    rating: 4.7,
    reviewsCount: 25,
    sku: "LL-TK-04",
    weightKg: 0.75,
    inStock: true,
    sizes: [
      { id: "52", name: "52" },
      { id: "54", name: "54" },
      { id: "56", name: "56" },
      { id: "58", name: "58" },
      { id: "60", name: "60" },
    ],
    includesSheila: false,
    specs: [
      { id: "design" },
      { id: "silhouette" },
      { id: "fabric" },
      { id: "color" },
      { id: "finishes", hasBullets: true },
      { id: "sleeves" },
      { id: "closure" },
    ],
    colors: [
      {
        id: "taupe",
        nameKey: "taupe",
        swatch: "taupe",
        images: ["/imgs/hero-slide-1.jpg", "/imgs/hero-slide-3.jpg"],
      },
      {
        id: "sand",
        nameKey: "sand",
        swatch: "sand",
        images: ["/imgs/hero-slide-2.jpg", "/imgs/hero-slide-1.jpg"],
      },
      {
        id: "ivory",
        nameKey: "ivory",
        swatch: "ivory",
        images: ["/imgs/hero-slide-2.jpg"],
      },
    ],
  },
];
